### ISSUE TITLE
Ship ability to create new todo things within a topic

### ISSUE THREAD

**Issue by dpaola2** [dpaola2/Tioga#4]
- [x] rails model
- [x] react component
- [x] include in schema other types of things
- [x] use react to render each thing
- [x] update topics#index to only show past topics that contain things, always show today, and only show tomorrow if it contains things
